<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblColorSizeCart</name>
   <tag></tag>
   <elementGuidId>589a5382-6033-47d0-b857-30c59d270375</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#layer_cart_product_attributes</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
