<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblPrice</name>
   <tag></tag>
   <elementGuidId>bf541aa4-7ec9-4729-8b11-9b4e9aa0bace</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#our_price_display</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
