<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblPriceProductCart</name>
   <tag></tag>
   <elementGuidId>9f966cf4-52b2-438e-ade4-392dea990988</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#layer_cart_product_price</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
