<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblProductCart</name>
   <tag></tag>
   <elementGuidId>b44ff3fa-4bc0-4021-9534-0de9277e7db4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#layer_cart_product_title</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
