<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblQuantityProductCart</name>
   <tag></tag>
   <elementGuidId>eee0d32a-a0da-4aa7-873d-abe8364f3513</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#layer_cart_product_quantity</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
